"""Initial migration

Revision ID: e3653595a6a4
Revises: 
Create Date: 2023-09-24 23:39:44.268197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3653595a6a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_model', sa.Column('genre', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_model', 'genre')
    # ### end Alembic commands ###
